### ISSUE TITLE
client/client.lua:29 Attempt to compare number with nil

### ISSUE THREAD

**Issue by DafkeDD** [jimathy/jim-recycle#6]
Hi Jim,

Any idea for fixing this one?
Thx man!

![afbeelding](https://user-images.githubusercontent.com/78157379/179022572-b83fb7ef-3df9-45ae-a10b-196ba4f58d73.png)

**Comment by jimathy** [comment]
fixed, forgot to add the starter variable, so it was trying to take 1 away from 'nil'
